### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by Mielesgames** [mmbaguette/Roblox-VR-with-Webcam#3]
The roblox testing game doesn't seem to give me an access token.
it shows that it has been generated in the console, but I can't find the token itself anywhere

**Comment by mmbaguette** [comment]
Yeah I turned off the server because you're the first one in a while to use this. I'll turn it on again just for you then you can try it again.

**Comment by mmbaguette** [comment]
It's up![image](https://user-images.githubusercontent.com/76597978/233842602-85226505-735c-429b-98a4-c33335e18ac6.jpeg)

**Comment by Mielesgames** [comment]
> It's up![image](https://user-images.githubusercontent.com/76597978/233842602-85226505-735c-429b-98a4-c33335e18ac6.jpeg)

Thank you, I will give it a try

**Comment by Mielesgames** [comment]
it seems that it gives a 404 error
![image](https://user-images.githubusercontent.com/83580270/233848191-35c16c25-cebe-4b36-9b54-138798b405b0.png)

**Comment by Mielesgames** [comment]
nvm I think I know what happened

**Comment by Mielesgames** [comment]
it works now

**Comment by mmbaguette** [comment]
It should be global. Did you delete your comment about it not being global? I'm confused.

**Comment by Mielesgames** [comment]
> It should be global. Did you delete your comment about it not being global? I'm confused.

my friend was confusing, he said he couldn't see it and 1 minute later he told me he was able to see it.
so that's why I edited the comment
